kind: Pod
apiVersion: v1
metadata:
  name: podname1
spec:
  containers:
    - name: cont2
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Moto; sleep 5 ; done"]
    - name: cont1
      image: httpd
      ports:
       - containerPort: 80

