apiVersion: v1
kind: Pod
metadata:
  name: podemptydir1
  kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: service1
spec:
  ports:
    - port: 80                               # Containers port exposed
      targetPort: 80                     # Pods port
  selector:

spec:
  containers:
  - name: cont1
    image: centos
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:                                    # Mount definition inside the container
      - name: xchange
        mountPath: "/tmp/xchange" #cont1 path where volume will be mount
  - name: cont2
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
      - name: xchange
        mountPath: "/tmp/data"
  volumes:
  - name: xchange
    emptyDir: {}

