apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
  - image: ubuntu
    name: cont1
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /tmp/vol1
      name: testvolume
  volumes:
  - name: testvolume
    hostPath:
      path: /home/ubuntu/

